In [1]:
# import modules
import numpy as np 
import cv2

In [2]:
# Set webcam
cap = cv2.VideoCapture(0)

# Detector Class 
detector = cv2.QRCodeDetector()


[ WARN:0@10.917] global /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_f6tvh9615u/croot/opencv-suite_1691620375715/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
2024-07-30 15:23:33.483 python[2501:49018] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.


In [3]:
while True: 

    success, img = cap.read()

    value, points, qrcode = detector.detectAndDecode(img)
    
    if value != "":
    
            x1 = points[0][0][0]
            y1 = points[0][0][1]
            x2 = points[0][2][0]
            y2 = points[0][2][1] 
      
            x_center = (x2 - x1) / 2 + x1
            y_center = (y2 - y1) / 2 + y1
      
            print(value)
            print(points)
            print(qrcode)

            cv2.rectangle(img, (int(x1), int(y1)), (int(x2), int(y2)), (0,255,0), 5)
            cv2.putText(img, str(value), (30, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2)

    cv2.imshow('Resultado', img)
    
    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllwindows() # close all windows when the program exits

https://github.com/catalina-lozano/data-Portfolio
[[[546.      203.     ]
  [789.      191.     ]
  [801.00006 431.     ]
  [560.      442.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255   0 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[551.      204.     ]
  [793.      186.     ]
  [810.5941  426.03027]
  [572.      445.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[561.      205.     ]
  [801.      187.     ]
  [818.35785 426.67438]
  [581.      444.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   

https://github.com/catalina-lozano/data-Portfolio
[[[437.     198.    ]
  [674.     174.    ]
  [696.622  407.6471]
  [468.     428.    ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[435.      198.     ]
  [671.      172.     ]
  [697.88354 406.7552 ]
  [468.      428.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[433.      199.     ]
  [670.      172.     ]
  [697.2816  406.70627]
  [465.      427.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0   0   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255   0 ... 255 255 255]
 [  0   0   0 ... 25

https://github.com/catalina-lozano/data-Portfolio
[[[402.      199.     ]
  [596.      186.     ]
  [609.80493 381.28168]
  [420.      391.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255   0 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[399.      198.     ]
  [592.      185.     ]
  [608.48315 380.87604]
  [417.      391.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[390.      199.     ]
  [586.      184.     ]
  [603.0669  381.85153]
  [411.      393.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255   0 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   

https://github.com/catalina-lozano/data-Portfolio
[[[373.      210.     ]
  [555.      198.     ]
  [568.1446  380.22678]
  [388.      388.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255   0 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255   0 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[358.      214.     ]
  [537.15295 199.     ]
  [554.      378.     ]
  [376.      389.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255   0 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[361.     213.    ]
  [543.     199.    ]
  [559.6558 382.2141]
  [380.     392.    ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 25

https://github.com/catalina-lozano/data-Portfolio
[[[426.      192.     ]
  [595.      216.     ]
  [558.4062  399.87003]
  [386.      364.     ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ...   0 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[426. 192.]
  [594. 215.]
  [559. 400.]
  [386. 364.]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0   0   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-lozano/data-Portfolio
[[[426.     192.    ]
  [595.     216.    ]
  [559.369  396.9269]
  [387.     365.    ]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255   0]]
https://github.com/catalina-

KeyboardInterrupt: 

In [2]:
# Constants
WINDOW_NAME = 'QR Code Detector'
FONT = cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 1
FONT_COLOR = (255, 255, 255)
RECTANGLE_COLOR = (0, 255, 0)
RECTANGLE_THICKNESS = 2
TEXT_POSITION = (30, 100)
ESC_KEY = 27

In [3]:
def draw_rectangle_with_text(img, points, text):
    # Print points for debugging
    print("Points structure:", points)

    x1, y1 = points[0]
    x2, y2 = points[2]
    
    # Draw rectangle
    cv2.rectangle(img, (int(x1), int(y1)), (int(x2), int(y2)), RECTANGLE_COLOR, RECTANGLE_THICKNESS)
    
    # Draw text
    cv2.putText(img, text, TEXT_POSITION, FONT, FONT_SCALE, FONT_COLOR, 2)


In [ ]:
def main():
    
    # Set webcam
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not open webcam.")
        return

    # QR Code detector
    detector = cv2.QRCodeDetector()

    while True:
        success, img = cap.read()
        if not success:
            print("Error: Could not read frame.")
            break

        value, points, _ = detector.detectAndDecode(img)

        if points is not None:
            points = points[0]  # Extract the first (and only) set of points
            draw_rectangle_with_text(img, points, value)
            print(f"QR Code detected: {value}")
            print(f"Points: {points}")

        cv2.imshow(WINDOW_NAME, img)
        
        # Check if the window was closed
        if cv2.getWindowProperty(WINDOW_NAME, cv2.WND_PROP_VISIBLE) < 1:
            break

        if cv2.waitKey(1) & 0xFF == ESC_KEY:
            break

    cap.release()
    cv2.destroyAllWindows()  # Close all windows when the program exits

if __name__ == "__main__":
    main()

[ WARN:0@335.361] global /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_f6tvh9615u/croot/opencv-suite_1691620375715/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created


Points structure: [[1277.  671.]
 [ 280.  717.]
 [ 680.   -0.]
 [1141.    0.]]
QR Code detected: 
Points: [[1277.  671.]
 [ 280.  717.]
 [ 680.   -0.]
 [1141.    0.]]
Points structure: [[727. 557.]
 [688. 717.]
 [286. 623.]
 [657. 488.]]
QR Code detected: 
Points: [[727. 557.]
 [688. 717.]
 [286. 623.]
 [657. 488.]]
Points structure: [[1277.     685.   ]
 [ 281.     717.   ]
 [ 655.575    0.   ]
 [1139.       0.   ]]
QR Code detected: 
Points: [[1277.     685.   ]
 [ 281.     717.   ]
 [ 655.575    0.   ]
 [1139.       0.   ]]
Points structure: [[1211.        686.      ]
 [1043.          0.      ]
 [  76.831314  633.0563  ]
 [ 113.        706.      ]]
QR Code detected: 
Points: [[1211.        686.      ]
 [1043.          0.      ]
 [  76.831314  633.0563  ]
 [ 113.        706.      ]]
Points structure: [[ 866.       105.     ]
 [1144.        97.     ]
 [1149.907    371.95627]
 [ 868.       356.     ]]
QR Code detected: 
Points: [[ 866.       105.     ]
 [1144.        97.     ]
 [1149.9

Points structure: [[ 769.       92.    ]
 [1058.       72.    ]
 [1074.5043  366.6835]
 [ 773.      368.    ]]
QR Code detected: 
Points: [[ 769.       92.    ]
 [1058.       72.    ]
 [1074.5043  366.6835]
 [ 773.      368.    ]]
Points structure: [[ 764.        73.     ]
 [1060.        49.     ]
 [1088.2212   349.54163]
 [ 770.       353.     ]]
QR Code detected: 
Points: [[ 764.        73.     ]
 [1060.        49.     ]
 [1088.2212   349.54163]
 [ 770.       353.     ]]
Points structure: [[ 768.        68.     ]
 [1079.        46.     ]
 [1096.6174   358.26642]
 [ 775.       359.     ]]
QR Code detected: 
Points: [[ 768.        68.     ]
 [1079.        46.     ]
 [1096.6174   358.26642]
 [ 775.       359.     ]]
Points structure: [[ 777.       81.    ]
 [1093.       60.    ]
 [1122.0752  385.    ]
 [ 783.      384.    ]]
QR Code detected: 
Points: [[ 777.       81.    ]
 [1093.       60.    ]
 [1122.0752  385.    ]
 [ 783.      384.    ]]
Points structure: [[ 768.       107.     ]
 

Points structure: [[415. 172.]
 [673. 139.]
 [706. 412.]
 [446. 430.]]
QR Code detected: 
Points: [[415. 172.]
 [673. 139.]
 [706. 412.]
 [446. 430.]]
Points structure: [[416. 175.]
 [676. 142.]
 [716. 419.]
 [446. 431.]]
QR Code detected: 
Points: [[416. 175.]
 [676. 142.]
 [716. 419.]
 [446. 431.]]
Points structure: [[424.      178.     ]
 [688.      148.     ]
 [716.7307  421.49008]
 [457.      439.     ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[424.      178.     ]
 [688.      148.     ]
 [716.7307  421.49008]
 [457.      439.     ]]
Points structure: [[428.     177.    ]
 [692.     147.    ]
 [720.1374 422.4122]
 [459.     440.    ]]
QR Code detected: 
Points: [[428.     177.    ]
 [692.     147.    ]
 [720.1374 422.4122]
 [459.     440.    ]]
Points structure: [[422.      175.     ]
 [684.      144.     ]
 [717.26245 418.67758]
 [453.      438.     ]]
QR Code detected: 
Points: [[422.      175.     ]
 [684.      144.     ]
 [717.26245 418.677

Points structure: [[347.      271.     ]
 [546.      244.     ]
 [584.5328  467.06714]
 [377.      481.     ]]
QR Code detected: 
Points: [[347.      271.     ]
 [546.      244.     ]
 [584.5328  467.06714]
 [377.      481.     ]]
Points structure: [[349.      271.     ]
 [550.      245.     ]
 [585.0559  468.37546]
 [379.      481.     ]]
QR Code detected: 
Points: [[349.      271.     ]
 [550.      245.     ]
 [585.0559  468.37546]
 [379.      481.     ]]
Points structure: [[348.     275.    ]
 [549.     248.    ]
 [587.0721 460.116 ]
 [380.     486.    ]]
QR Code detected: 
Points: [[348.     275.    ]
 [549.     248.    ]
 [587.0721 460.116 ]
 [380.     486.    ]]
Points structure: [[345.      279.     ]
 [545.      252.     ]
 [576.88654 478.09235]
 [377.      490.     ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[345.      279.     ]
 [545.      252.     ]
 [576.88654 478.09235]
 [377.      490.     ]]
Points structure: [[339.      280.     ]
 [

Points structure: [[416.     315.    ]
 [612.     294.    ]
 [646.8759 508.7925]
 [444.     516.    ]]
QR Code detected: 
Points: [[416.     315.    ]
 [612.     294.    ]
 [646.8759 508.7925]
 [444.     516.    ]]
Points structure: [[411.      318.     ]
 [610.      297.     ]
 [637.9028  515.38043]
 [440.      523.     ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[411.      318.     ]
 [610.      297.     ]
 [637.9028  515.38043]
 [440.      523.     ]]
Points structure: [[407.     323.    ]
 [610.     302.    ]
 [649.0596 526.669 ]
 [438.     533.    ]]
QR Code detected: 
Points: [[407.     323.    ]
 [610.     302.    ]
 [649.0596 526.669 ]
 [438.     533.    ]]
Points structure: [[407.      328.     ]
 [613.      308.     ]
 [645.78076 535.7183 ]
 [437.      541.     ]]
QR Code detected: 
Points: [[407.      328.     ]
 [613.      308.     ]
 [645.78076 535.7183 ]
 [437.      541.     ]]
Points structure: [[406.      337.     ]
 [615.      318.  

Points structure: [[558.003   124.83926]
 [769.      133.     ]
 [760.71246 354.92426]
 [554.      339.     ]]
QR Code detected: 
Points: [[558.003   124.83926]
 [769.      133.     ]
 [760.71246 354.92426]
 [554.      339.     ]]
Points structure: [[557.      127.     ]
 [767.      133.     ]
 [759.44226 356.65607]
 [553.      340.     ]]
QR Code detected: 
Points: [[557.      127.     ]
 [767.      133.     ]
 [759.44226 356.65607]
 [553.      340.     ]]
Points structure: [[552.      132.     ]
 [763.      138.     ]
 [756.33203 357.70245]
 [550.      346.     ]]
QR Code detected: 
Points: [[552.      132.     ]
 [763.      138.     ]
 [756.33203 357.70245]
 [550.      346.     ]]
Points structure: [[550. 155.]
 [756. 156.]
 [761. 367.]
 [553. 367.]]
QR Code detected: 
Points: [[550. 155.]
 [756. 156.]
 [761. 367.]
 [553. 367.]]
Points structure: [[547.      153.     ]
 [756.      152.     ]
 [761.0567  358.80136]
 [553.      362.     ]]
QR Code detected: 
Points: [[547.      153.  

Points structure: [[459.       90.     ]
 [671.      126.     ]
 [643.5436  337.23007]
 [435.      315.     ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[459.       90.     ]
 [671.      126.     ]
 [643.5436  337.23007]
 [435.      315.     ]]
Points structure: [[459.      90.    ]
 [672.     127.    ]
 [642.3419 346.7248]
 [434.     315.    ]]
QR Code detected: 
Points: [[459.      90.    ]
 [672.     127.    ]
 [642.3419 346.7248]
 [434.     315.    ]]
Points structure: [[460.       89.     ]
 [671.      126.     ]
 [642.4732  344.53412]
 [434.      317.     ]]
QR Code detected: 
Points: [[460.       89.     ]
 [671.      126.     ]
 [642.4732  344.53412]
 [434.      317.     ]]
Points structure: [[459.       89.     ]
 [671.      127.     ]
 [641.4655  347.74155]
 [433.      316.     ]]
QR Code detected: 
Points: [[459.       89.     ]
 [671.      127.     ]
 [641.4655  347.74155]
 [433.      316.     ]]
Points structure: [[459.       89.     ]
 [

Points structure: [[412. 109.]
 [648. 146.]
 [620. 376.]
 [386. 347.]]
QR Code detected: 
Points: [[412. 109.]
 [648. 146.]
 [620. 376.]
 [386. 347.]]
Points structure: [[412. 107.]
 [646. 145.]
 [618. 374.]
 [384. 346.]]
QR Code detected: 
Points: [[412. 107.]
 [646. 145.]
 [618. 374.]
 [384. 346.]]
Points structure: [[405.      106.     ]
 [642.      145.     ]
 [604.0949  376.02612]
 [378.      344.     ]]
QR Code detected: 
Points: [[405.      106.     ]
 [642.      145.     ]
 [604.0949  376.02612]
 [378.      344.     ]]
Points structure: [[400. 105.]
 [637. 142.]
 [603. 376.]
 [375. 343.]]
QR Code detected: 
Points: [[400. 105.]
 [637. 142.]
 [603. 376.]
 [375. 343.]]
Points structure: [[401.      107.     ]
 [639.      143.     ]
 [603.44617 376.44263]
 [377.      344.     ]]
QR Code detected: 
Points: [[401.      107.     ]
 [639.      143.     ]
 [603.44617 376.44263]
 [377.      344.     ]]
Points structure: [[404.      108.     ]
 [642.      144.     ]
 [605.87103 373.2041 

Points structure: [[316.       96.     ]
 [561.      127.     ]
 [537.399   352.60913]
 [304.      337.     ]]
QR Code detected: 
Points: [[316.       96.     ]
 [561.      127.     ]
 [537.399   352.60913]
 [304.      337.     ]]
Points structure: [[312.       97.     ]
 [557.      125.     ]
 [534.49146 363.36172]
 [301.      336.     ]]
QR Code detected: 
Points: [[312.       97.     ]
 [557.      125.     ]
 [534.49146 363.36172]
 [301.      336.     ]]
Points structure: [[315.  96.]
 [561. 127.]
 [538. 364.]
 [304. 336.]]
QR Code detected: 
Points: [[315.  96.]
 [561. 127.]
 [538. 364.]
 [304. 336.]]
Points structure: [[318.      98.    ]
 [566.     128.    ]
 [541.4876 352.9815]
 [309.     337.    ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[318.      98.    ]
 [566.     128.    ]
 [541.4876 352.9815]
 [309.     337.    ]]
Points structure: [[320.       98.     ]
 [567.      129.     ]
 [540.2276  363.25705]
 [308.      336.     ]]
QR Code dete

Points structure: [[202.      108.     ]
 [477.      136.     ]
 [470.97787 377.84094]
 [208.      361.     ]]
QR Code detected: 
Points: [[202.      108.     ]
 [477.      136.     ]
 [470.97787 377.84094]
 [208.      361.     ]]
Points structure: [[180.      104.     ]
 [456.      129.     ]
 [445.55038 371.52917]
 [192.      358.     ]]
QR Code detected: 
Points: [[180.      104.     ]
 [456.      129.     ]
 [445.55038 371.52917]
 [192.      358.     ]]
Points structure: [[164.      102.     ]
 [437.      122.     ]
 [432.84537 380.64792]
 [178.      353.     ]]
QR Code detected: 
Points: [[164.      102.     ]
 [437.      122.     ]
 [432.84537 380.64792]
 [178.      353.     ]]
Points structure: [[162. 101.]
 [432. 120.]
 [443. 378.]
 [177. 354.]]
QR Code detected: 
Points: [[162. 101.]
 [432. 120.]
 [443. 378.]
 [177. 354.]]
Points structure: [[160.      101.     ]
 [431.      118.     ]
 [431.00003 372.     ]
 [176.      350.     ]]
QR Code detected: 
Points: [[160.      101.  

Points structure: [[209.      113.     ]
 [491.      142.     ]
 [476.62027 400.76572]
 [216.      373.     ]]
QR Code detected: 
Points: [[209.      113.     ]
 [491.      142.     ]
 [476.62027 400.76572]
 [216.      373.     ]]
Points structure: [[212.      112.     ]
 [492.      143.     ]
 [477.13043 392.91306]
 [217.      373.     ]]
QR Code detected: 
Points: [[212.      112.     ]
 [492.      143.     ]
 [477.13043 392.91306]
 [217.      373.     ]]
Points structure: [[210.      115.     ]
 [494.      143.     ]
 [478.94345 406.33875]
 [218.      373.     ]]
QR Code detected: 
Points: [[210.      115.     ]
 [494.      143.     ]
 [478.94345 406.33875]
 [218.      373.     ]]
Points structure: [[215. 115.]
 [495. 142.]
 [484. 410.]
 [221. 376.]]
QR Code detected: 
Points: [[215. 115.]
 [495. 142.]
 [484. 410.]
 [221. 376.]]
Points structure: [[219.      118.     ]
 [502.      148.     ]
 [486.3235  407.59363]
 [224.      380.     ]]
QR Code detected: 
Points: [[219.      118.  

Points structure: [[187.      121.     ]
 [476.      150.     ]
 [463.50558 417.43973]
 [198.      384.     ]]
QR Code detected: 
Points: [[187.      121.     ]
 [476.      150.     ]
 [463.50558 417.43973]
 [198.      384.     ]]
Points structure: [[185.      120.     ]
 [472.      147.     ]
 [463.0468  405.48895]
 [197.      384.     ]]
QR Code detected: 
Points: [[185.      120.     ]
 [472.      147.     ]
 [463.0468  405.48895]
 [197.      384.     ]]
Points structure: [[187.      120.     ]
 [476.      146.     ]
 [465.33887 414.35977]
 [200.      381.     ]]
QR Code detected: 
Points: [[187.      120.     ]
 [476.      146.     ]
 [465.33887 414.35977]
 [200.      381.     ]]
Points structure: [[187.      119.     ]
 [475.      146.     ]
 [464.52417 400.5291 ]
 [199.      383.     ]]
QR Code detected: 
Points: [[187.      119.     ]
 [475.      146.     ]
 [464.52417 400.5291 ]
 [199.      383.     ]]
Points structure: [[179.     121.    ]
 [467.     146.    ]
 [458.5416 408.1

Points structure: [[268. 126.]
 [553. 159.]
 [530. 432.]
 [264. 388.]]
QR Code detected: 
Points: [[268. 126.]
 [553. 159.]
 [530. 432.]
 [264. 388.]]
Points structure: [[270.      126.     ]
 [555.      161.     ]
 [529.93256 413.8863 ]
 [266.      390.     ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[270.      126.     ]
 [555.      161.     ]
 [529.93256 413.8863 ]
 [266.      390.     ]]
Points structure: [[268. 127.]
 [552. 157.]
 [531. 414.]
 [265. 388.]]
QR Code detected: 
Points: [[268. 127.]
 [552. 157.]
 [531. 414.]
 [265. 388.]]
Points structure: [[268.      126.     ]
 [554.      161.     ]
 [527.4545  433.53046]
 [264.      389.     ]]
QR Code detected: 
Points: [[268.      126.     ]
 [554.      161.     ]
 [527.4545  433.53046]
 [264.      389.     ]]
Points structure: [[267.      127.     ]
 [551.      158.     ]
 [530.      423.00003]
 [264.      390.     ]]
QR Code detected: 
Points: [[267.      127.     ]
 [551.      158.     ]
 [5

Points structure: [[256. 138.]
 [550. 171.]
 [534. 435.]
 [255. 407.]]
QR Code detected: 
Points: [[256. 138.]
 [550. 171.]
 [534. 435.]
 [255. 407.]]
Points structure: [[253.      137.     ]
 [547.      172.     ]
 [522.14404 436.93234]
 [251.      405.     ]]
QR Code detected: 
Points: [[253.      137.     ]
 [547.      172.     ]
 [522.14404 436.93234]
 [251.      405.     ]]
Points structure: [[245.     136.    ]
 [539.     169.    ]
 [516.7016 428.1631]
 [246.     405.    ]]
QR Code detected: https://github.com/catalina-lozano/data-Portfolio
Points: [[245.     136.    ]
 [539.     169.    ]
 [516.7016 428.1631]
 [246.     405.    ]]
Points structure: [[239.      135.     ]
 [534.      167.     ]
 [512.15234 437.6997 ]
 [242.      404.     ]]
QR Code detected: 
Points: [[239.      135.     ]
 [534.      167.     ]
 [512.15234 437.6997 ]
 [242.      404.     ]]
Points structure: [[241. 135.]
 [534. 167.]
 [517. 432.]
 [242. 404.]]
QR Code detected: 
Points: [[241. 135.]
 [534. 167.]

Points structure: [[191.      139.     ]
 [494.      170.     ]
 [479.64902 444.24622]
 [200.      413.     ]]
QR Code detected: 
Points: [[191.      139.     ]
 [494.      170.     ]
 [479.64902 444.24622]
 [200.      413.     ]]
Points structure: [[189.      139.     ]
 [491.      167.     ]
 [479.76132 437.2594 ]
 [201.      415.     ]]
QR Code detected: 
Points: [[189.      139.     ]
 [491.      167.     ]
 [479.76132 437.2594 ]
 [201.      415.     ]]
Points structure: [[187.      138.     ]
 [491.      167.     ]
 [478.1515  445.41516]
 [199.      413.     ]]
QR Code detected: 
Points: [[187.      138.     ]
 [491.      167.     ]
 [478.1515  445.41516]
 [199.      413.     ]]
Points structure: [[191.      134.     ]
 [495.      159.     ]
 [481.96567 439.99237]
 [205.      406.     ]]
QR Code detected: 
Points: [[191.      134.     ]
 [495.      159.     ]
 [481.96567 439.99237]
 [205.      406.     ]]
Points structure: [[195.      133.     ]
 [495.      163.     ]
 [481.52274 

Points structure: [[ 683.        0.    ]
 [1007.2636  717.    ]
 [  -0.      717.    ]
 [   0.       91.    ]]
QR Code detected: 
Points: [[ 683.        0.    ]
 [1007.2636  717.    ]
 [  -0.      717.    ]
 [   0.       91.    ]]
Points structure: [[506.   0.]
 [  0.  90.]
 [ -0. 409.]
 [465. 654.]]
QR Code detected: 
Points: [[506.   0.]
 [  0.  90.]
 [ -0. 409.]
 [465. 654.]]
Points structure: [[1025.         717.       ]
 [ 801.           0.       ]
 [  -1.6548673    0.       ]
 [  60.         717.       ]]
QR Code detected: 
Points: [[1025.         717.       ]
 [ 801.           0.       ]
 [  -1.6548673    0.       ]
 [  60.         717.       ]]
Points structure: [[ 87. 717.]
 [  0.  91.]
 [231.   0.]
 [561. 717.]]
QR Code detected: 
Points: [[ 87. 717.]
 [  0.  91.]
 [231.   0.]
 [561. 717.]]
Points structure: [[748.  64.]
 [568. 640.]
 [444. 717.]
 [  0.  91.]]
QR Code detected: 
Points: [[748.  64.]
 [568. 640.]
 [444. 717.]
 [  0.  91.]]
Points structure: [[704.     299.    